export const qualifications = [
  "High School Diploma (Science with Biology)",
  "Pre-Medical Course",
  "Paramedical Diploma",
  "Diploma in Nursing",
  "Diploma in Medical Lab Technology (DMLT)",
  "Diploma in Radiology",
  "Diploma in Physiotherapy",
  "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
  "BDS (Bachelor of Dental Surgery)",
  "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
  "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
  "BUMS (Bachelor of Unani Medicine and Surgery)",
  "BNYS (Bachelor of Naturopathy and Yogic Sciences)",
  "BSMS (Bachelor of Siddha Medicine and Surgery)",
  "BPT (Bachelor of Physiotherapy)",
  "BOT (Bachelor of Occupational Therapy)",
  "B.Sc Nursing",
  "B.Sc Optometry",
  "B.Sc Medical Lab Technology",
  "B.Sc Radiology",
  "B.Sc Anesthesia Technology",
  "B.Sc Cardiovascular Technology",
  "B.Sc Biotechnology",
  "MD (Doctor of Medicine)",
  "MS (Master of Surgery)",
  "MDS (Master of Dental Surgery)",
  "MPT (Master of Physiotherapy)",
  "MOT (Master of Occupational Therapy)",
  "M.Sc Nursing",
  "M.Sc Clinical Research",
  "M.Sc Medical Lab Technology",
  "M.Sc Radiology",
  "M.Sc Biotechnology",
  "MPH (Master of Public Health)",
  "MBA in Hospital Management",
  "MHA (Master of Health Administration)",
  "DM (Doctorate of Medicine - Super Specialization)",
  "MCh (Magister Chirurgiae - Super Specialization Surgery)",
  "FNB (Fellow of National Board)",
  "DNB (Diplomate of National Board)",
  "Fellowship in Cardiology",
  "Fellowship in Neurology",
  "Fellowship in Oncology",
  "Fellowship in Pediatrics",
  "Fellowship in Critical Care",
  "Fellowship in Minimal Access Surgery",
  "Fellowship in Dermatology",
  "Fellowship in Endocrinology",
  "Fellowship in Emergency Medicine",
  "PhD in Medicine",
  "PhD in Nursing",
  "PhD in Clinical Research",
  "PhD in Biomedical Sciences",
  "MPhil in Medical Sciences",
  "PG Diploma in Clinical Cardiology",
  "PG Diploma in Diabetology",
  "PG Diploma in Emergency Medicine",
  "PG Diploma in Hospital Management",
  "PG Diploma in Radiodiagnosis",
  "PG Diploma in Obstetrics and Gynecology",
  "PG Diploma in Anesthesia",
  "Certificate in Medical Transcription",
  "Certificate in ECG Technology",
  "Certificate in Dialysis Technology",
  "Certificate in Medical Imaging",
  "Certificate in Home Based Care",
  "Others"
];

export const specialties = [
  "Acupuncturist",
  "Anesthesiologist",
  "Audiologist",
  "Ayurvedic Doctor",
  "Cardiologist",
  "Cardiothoracic Surgeon",
  "Chiropractor",
  "Cosmetologist",
  "Critical Care Specialist",
  "Dentist",
  "Dermatologist",
  "Diabetologist",
  "Emergency Medicine Specialist",
  "Endocrinologist",
  "Endodontist",
  "Family Medicine",
  "Fertility Specialist",
  "Gastroenterologist",
  "General Practitioner (GP)",
  "General Physician",
  "Gynecologist",
  "Hematologist",
  "Hepatologist",
  "Homeopathic Doctor",
  "Internal Medicine",
  "Neonatologist",
  "Nephrologist",
  "Neurologist",
  "Neurosurgeon",
  "Naturopathic Doctor",
  "Nuclear Medicine Specialist",
  "Obstetrician",
  "Oncologist (Medical)",
  "Ophthalmologist",
  "Optometrist",
  "Oral & Maxillofacial Surgeon",
  "Orthodontist",
  "Orthopedic Surgeon",
  "Otolaryngologist (ENT Specialist)",
  "Pathologist",
  "Pediatric Dentist",
  "Pediatric Surgeon",
  "Pediatrician",
  "Periodontist",
  "Physiatrist",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist",
  "Radiation Oncologist",
  "Radiologist",
  "Reproductive Endocrinologist",
  "Rheumatologist",
  "Sports Medicine Specialist",
  "Surgical Oncologist",
  "Thoracic Surgeon",
  "Trichologist",
  "Urologist",
  "Vascular Surgeon",
  "Others"
];

export const medicalCouncils = [
  "National Medical Commission (NMC)",
  "Andhra Pradesh Medical Council",
  "Assam Medical Council",
  "Bihar Medical Council",
  "Chhattisgarh Medical Council",
  "Delhi Medical Council",
  "Goa Medical Council",
  "Gujarat Medical Council",
  "Haryana Medical Council",
  "Himachal Pradesh Medical Council",
  "Jammu & Kashmir Medical Council",
  "Jharkhand Medical Council",
  "Karnataka Medical Council",
  "Kerala Medical Council",
  "Madhya Pradesh Medical Council",
  "Maharashtra Medical Council",
  "Manipur Medical Council",
  "Meghalaya Medical Council",
  "Mizoram Medical Council",
  "Nagaland Medical Council",
  "Odisha Council of Medical Registration",
  "Punjab Medical Council",
  "Rajasthan Medical Council",
  "Sikkim Medical Council",
  "Tamil Nadu Medical Council",
  "Telangana State Medical Council",
  "Tripura State Medical Council",
  "Uttar Pradesh Medical Council",
  "Uttarakhand Medical Council",
  "West Bengal Medical Council",
  "Others"
];

export const departments = [
  "Pediatrics",
  "IT Department",
  "Endocrinology",
  "Billing Department",
  "General Medicine",
  "Emergency Department",
  "Test",
  "Dermatology",
  "Gastroenterology"
];

export const employmentTypes = [
  "Full-Time",
  "Part-Time",
  "Contractual",
  "Visiting Consultant",
  "On-Call",
  "Resident",
  "Probationary",
  "Temporary",
  "Intern / Trainee",
  "Volunteer",
  "Outsourced",
  "Honorary",
  "Locum (Temporary Replacement)",
  "Others"
];

export const maritalStatuses = [
  "Married",
  "Unmarried",
  "Divorced",
  "Widowed"
];
